name = "LineageCollapse"
uuid = "e38bdfdf-80f5-4f0c-93e0-53dd02ee37b8"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com> and contributors"]
version = "0.0.7"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
VisualizationExt = "CairoMakie"

[compat]
BioSequences = "3.1.6"
CSV = "0.10.14"
CairoMakie = "0.12.13"
Clustering = "0.15.7"
DataFrames = "1.7.0"
ProgressMeter = "1.10.2"
StringDistances = "0.11.3"
julia = "1.10"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie"]
