name = "LineageCollapse"
uuid = "e38bdfdf-80f5-4f0c-93e0-53dd02ee37b8"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com> and contributors"]
version = "0.0.16"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"

[compat]
BioSequences = "3.1.6"
CSV = "0.10.14"
Clustering = "0.15.7"
DataFrames = "1.7.0"
LinearAlgebra = "1.11.0"
ProgressMeter = "1.10.2"
SparseArrays = "1.11.0"
StringDistances = "0.11.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
